### ISSUE TITLE
make tar_make at cursor have a controllable `shortcut` option

### ISSUE THREAD

**Issue by njtierney** [MilesMcBain/tflow#13]
currently the make target at cursor addin runs

`tar_make(name, shortcut = TRUE)`

https://github.com/MilesMcBain/tflow/blob/master/R/addins.R#L61

However my default for this that I would like it rerun everything upstream - is it possible to control that `shortcut` option?

**Comment by MilesMcBain** [comment]
Yeah but an option is kind of annoying if you want the other one. Let's just have both!

**Comment by MilesMcBain** [comment]
Done!
