### ISSUE TITLE
Package installation depends on R >= 4.1 since it depends on native pipe

### ISSUE THREAD

**Issue by alaindanet** [MilesMcBain/tflow#16]
Hi,

thank you so much for your package.

I have encountered an error while installing your package.
```
* installing *source* package ‘tflow’ ...
** using staged installation
** R
Error in parse(outFile) :
  /tmp/RtmpeseGMu/R.INSTALL69a265b1ba1/tflow/R/addins.R:129:71: '>' inatte
ndu(e)
128: parse_targets_yaml <- function() {
129:   yaml::read_yaml("../interactive_location_analytics/_targets.yaml")
|>

 ^
ERROR: unable to collate and parse R files for package ‘tflow’
* removing ‘/home/alain/R/x86_64-pc-linux-gnu-library/4.0/tflow’
```
The parsing error point toward the pipe operator "|>" which was included in R in version 4.1.0. 

Since I use R 4.0.5, the installation failed.

**Comment by MilesMcBain** [comment]
Ah thanks, a bit of careless coding, sorry. I've removed the `|>` and `\()` so hopefully things go smoothly now.

**Comment by alaindanet** [comment]
Thank you so much, the installation has worked! Looking forward to discover `targets` and `tflow`!
